config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "pages#home"
  resources :projects
  get '/components', to: 'pages#components', as: 'components'
  get '/inquiries', to: 'inquiries#new', as: 'new_inquiry'
  post '/inquiries', to: 'inquiries#create', as: 'inquiries'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
    validates :email, 
    presence: true,
    format: { 
      with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i,
      message: "must be a valid email address"
    }
  validates :description, presence: true
  validates :name, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
    def new
        @project = Project.new
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
    def new
        @inquiry = Inquiry.new
    end

    def create
        @inquiry = Inquiry.new(inquiry_params)
        if @inquiry.save
            InquiriesMailer.general_message(@inquiry).deliver
            respond_to do |format|
                format.html { redirect_to root_path, notice: 'Inquiry was successfully sent!' }
            end
          else
            render :new
          end
    end

    private

    def inquiry_params
        params.require('inquiry').permit(:name, :email, :phone, :website, :budget, :description)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
  
    def components
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/inquiries/new.html.erb
<div class='inquiry-form'>
    <%= simple_form_for(@inquiry) do |f| %>
        <h1 style='text-align: center'>Let's work together!</h1>
        <br>
        <p style='font-weight: bold'>Please complete the form below to inquire about working together. <br> General messages may also be sent using the below form.</p>
        <br>
        <p><%= f.input :name, label: 'Name:'%></p> 
        <p><%= f.input :email, label: 'Email:'%></p>
        <p><%= f.input :phone, label: 'Phone:' %></p>
        <p><%= f.input :website, label: 'Current website:' %></p>
        <p><%= f.input :budget, label: 'Budget:' %></p>
        <p><%= f.input :description, as: :text, label: 'Description:', input_html: { style: 'height: 50vh; width: 100%'} %></p>
        <%= f.submit 'Inquire', class: 'btn btn-primary', style: 'margin-top: 10px; width: 100px;'%>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Joel Velis</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <%= yield %>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <footer>
      <ul>
          <li><a href='https://www.instagram.com/jayemveeyu/?hl=en' style='color: #ffffff'><i class="fa fa-instagram"></i></a></li>
          <li><a href='https://www.linkedin.com/in/joel-velis/' style='color: #ffffff'><i class="fa fa-linkedin"></a></i></li>
          <li><a href='https://github.com/jvelis94' style='color: #ffffff'><i class="fa fa-github"></i></a></li>
      </ul>
    <footer>
  </body>
</html>

app/views/pages/components.html.erb
<%# Navbar %>
<div class='nav-bar-size'>
      <div class='nav-container'>
          <div class='nav-logo'>
              <p style='margin: 0'><%= link_to image_tag('J.jpg', height: 50, width: 50, style: 'border-radius: 50%'), root_path %> Joel Velis</p>
          </div>
          <div class='nav-options'>
              <ul class='nav-list'>
                  <li><%= link_to 'About', root_path %></li>
                  <li><%= link_to 'Portfolio', root_path %></li>
                  <li><%= link_to 'Hire Joel', root_path %></li>
              </ul>
          </div>
      </div>
      <div class='mobile-nav'>
          <div class='nav-container-mobile'>
              <div class='nav-logo'>
                  <p style='margin: 0'><%= link_to image_tag('https://st3.depositphotos.com/9543826/13008/v/950/depositphotos_130085330-stock-illustration-j-v-letters-logo.jpg', height: 50, width: 50, style: 'border-radius: 50%'), root_path %> Joel Velis</p>
              </div>
              <a href="javascript:void(0);" style='color: black; font-size: 24px' class="icon" onclick="navBar()">
                  <i class="fa fa-bars"></i>
              </a>
          </div>
          <div class='nav-options'>
              <ul class='nav-list-mobile'>
                  <li><%= link_to 'About', root_path %></li>
                  <li><%= link_to 'Portfolio', root_path %></li>
                  <li><%= link_to 'Hire Joel', root_path %></li>
              </ul>
          </div>
      </div>
</div>
<footer>
      <ul>
          <li><i class="fa fa-instagram"></i></li>
          <li><i class="fa fa-linkedin"></i></li>
          <li><i class="fa fa-github"></i></li>
      </ul>
    <footer>

app/views/pages/home.html.erb
<div class='page-default-size'>
    <div class='home-blurb'>
        <h1>Full Stack Developer</h1>
        <h1>Business Strategist</h1>
        <p>Helping start-ups and small businesses develop high grade websites and exceptional user experience to drive user flow</p>
        <a href="#portfolio" class="arrow-down">View Portfolio</a>
    </div>
</div>
<div id='portfolio'>
    <div class='item-wrapper'>
        <%= link_to image_tag('split_logo.png', height: 100, width: 100, style: 'background-color: #ffffff'), 'http://split-calc.herokuapp.com', style: 'background-color: #ffffff' %>
        <p class="text">React, Mobile</p>
    </div>
    <div class='item-wrapper'>
        <%= link_to image_tag('mutable_matter_logo.png', height: 100, width: 100, style: 'background-color: #ffffff'), 'http://mutable-matter.herokuapp.com', style: 'background-color: #ffffff' %>
        <p class="text">Rails, HTML5, CSS3, Responsive</p>
    </div>
    <div class='item-wrapper'>
        <a href='https://www.farmersemarket.co/' style='background-color: #384D48'>Farmers' eMarket</a>
        <p class="text">Rails, HTML5, CSS3, Desktop only</p>
    </div>
    <div class='item-wrapper'>
        <a href='https://lujo-cars.herokuapp.com/' style='background-color: #000000'>Lujo</a>
        <p class="text">Rails, HTML5, CSS3, Desktop only</p>
    </div>
</div>
<div id='value-prop'>
    <section style='background-color: #ffffff'>
        <h1 style='background-color: #ffffff'>Lets work together!</h1><br>
        <p style='background-color: #ffffff'>Whether you are a developer looking for collaboration or a business owner looking 
        to create an online presence or seek consultancy, let's get in touch. I have experience in:</p><br>
        <p class='experience' style='background-color: #ffffff'>Creating responsive websites that work on desktop, tablet and mobile</p>
        <p class='experience' style='background-color: #ffffff'>Working with a design template or designing my own, based on need</p>
        <p class='experience' style='background-color: #ffffff'>Working with non-technical individuals</p>
        <p class='experience' style='background-color: #ffffff'>Finance business strategy</p>
    <section>
</div>

app/views/shared/_navbar.html.erb
<%# Navbar %>
<div class='nav-bar-size'>
      <div class='nav-container'>
          <div class='nav-logo'>
              <p style='margin: 0; font-weight: bold; color: #ffffff'><%= link_to image_tag('J.png', height: 50, width: 50, style: 'border-radius: 50%'), root_path, style: 'margin-right: 10px' %> Joel Velis</p>
          </div>
          <div class='nav-options'>
              <ul class='nav-list'>
                  <li><%= link_to 'About', root_path %></li>
                  <li><%= link_to 'Portfolio', '#portfolio' %></li>
                  <li><%= link_to 'Hire Joel', inquiries_path %></li>
              </ul>
          </div>
      </div>
      <div class='mobile-nav'>
          <div class='nav-container-mobile'>
              <div class='nav-logo'>
                  <p style='margin: 0; color: #ffffff''><%= link_to image_tag('J.png', height: 50, width: 50, style: 'border-radius: 50%'), root_path %> Joel Velis</p>
              </div>
              <a href="javascript:void(0);" style='color: black; font-size: 24px' class="icon" onclick="navBar()">
                  <i class="fa fa-bars" style='color: #ffffff'></i>
              </a>
          </div>
          <div class='nav-options'>
              <ul class='nav-list-mobile'>
                  <li><%= link_to 'About', root_path %></li>
                  <li><%= link_to 'Portfolio', '#portfolio' %></li>
                  <li><%= link_to 'Hire Joel', inquiries_path %></li>
              </ul>
          </div>
      </div>
</div>

<script>
    
</script>